package su.kaoyu.glyph.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import su.kaoyu.glyph.dao.GlyphName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GLYPH_NAME".
*/
public class GlyphNameDao extends AbstractDao<GlyphName, String> {

    public static final String TABLENAME = "GLYPH_NAME";

    /**
     * Properties of entity GlyphName.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property GlyphName = new Property(0, String.class, "glyphName", true, "GLYPH_NAME");
        public final static Property GlyphId = new Property(1, long.class, "glyphId", false, "GLYPH_ID");
    };

    private DaoSession daoSession;


    public GlyphNameDao(DaoConfig config) {
        super(config);
    }
    
    public GlyphNameDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GLYPH_NAME\" (" + //
                "\"GLYPH_NAME\" TEXT PRIMARY KEY NOT NULL ," + // 0: glyphName
                "\"GLYPH_ID\" INTEGER NOT NULL );"); // 1: glyphId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GLYPH_NAME\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GlyphName entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getGlyphName());
        stmt.bindLong(2, entity.getGlyphId());
    }

    @Override
    protected void attachEntity(GlyphName entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GlyphName readEntity(Cursor cursor, int offset) {
        GlyphName entity = new GlyphName( //
            cursor.getString(offset + 0), // glyphName
            cursor.getLong(offset + 1) // glyphId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GlyphName entity, int offset) {
        entity.setGlyphName(cursor.getString(offset + 0));
        entity.setGlyphId(cursor.getLong(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(GlyphName entity, long rowId) {
        return entity.getGlyphName();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(GlyphName entity) {
        if(entity != null) {
            return entity.getGlyphName();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGlyphDao().getAllColumns());
            builder.append(" FROM GLYPH_NAME T");
            builder.append(" LEFT JOIN GLYPH T0 ON T.\"GLYPH_ID\"=T0.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected GlyphName loadCurrentDeep(Cursor cursor, boolean lock) {
        GlyphName entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Glyph glyph = loadCurrentOther(daoSession.getGlyphDao(), cursor, offset);
         if(glyph != null) {
            entity.setGlyph(glyph);
        }

        return entity;    
    }

    public GlyphName loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<GlyphName> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<GlyphName> list = new ArrayList<GlyphName>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<GlyphName> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<GlyphName> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
